// Code generated by MockGen. DO NOT EDIT.
// Source: wrapper.go

// Package mock_src is a generated GoMock package.
package wrappermock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	googleapi "google.golang.org/api/googleapi"
	v1 "google.golang.org/api/tasks/v1"
)

// MockTODOOpWrapper is a mock of TODOOpWrapper interface
type MockTODOOpWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockTODOOpWrapperMockRecorder
}

// MockTODOOpWrapperMockRecorder is the mock recorder for MockTODOOpWrapper
type MockTODOOpWrapperMockRecorder struct {
	mock *MockTODOOpWrapper
}

// NewMockTODOOpWrapper creates a new mock instance
func NewMockTODOOpWrapper(ctrl *gomock.Controller) *MockTODOOpWrapper {
	mock := &MockTODOOpWrapper{ctrl: ctrl}
	mock.recorder = &MockTODOOpWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTODOOpWrapper) EXPECT() *MockTODOOpWrapperMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockTODOOpWrapper) List(maxCount int64, opts ...googleapi.CallOption) (*v1.TaskLists, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{maxCount}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*v1.TaskLists)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockTODOOpWrapperMockRecorder) List(maxCount interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{maxCount}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTODOOpWrapper)(nil).List), varargs...)
}

// Insert mocks base method
func (m *MockTODOOpWrapper) Insert(tasklist *v1.TaskList, opts ...googleapi.CallOption) (*v1.TaskList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklist}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(*v1.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockTODOOpWrapperMockRecorder) Insert(tasklist interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklist}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTODOOpWrapper)(nil).Insert), varargs...)
}

// Update mocks base method
func (m *MockTODOOpWrapper) Update(tasklistid string, tasklist *v1.TaskList, opts ...googleapi.CallOption) (*v1.TaskList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid, tasklist}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*v1.TaskList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockTODOOpWrapperMockRecorder) Update(tasklistid, tasklist interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid, tasklist}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTODOOpWrapper)(nil).Update), varargs...)
}

// Delete mocks base method
func (m *MockTODOOpWrapper) Delete(tasklistid string, opts ...googleapi.CallOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockTODOOpWrapperMockRecorder) Delete(tasklistid interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTODOOpWrapper)(nil).Delete), varargs...)
}

// MockTaskOpWrapper is a mock of TaskOpWrapper interface
type MockTaskOpWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockTaskOpWrapperMockRecorder
}

// MockTaskOpWrapperMockRecorder is the mock recorder for MockTaskOpWrapper
type MockTaskOpWrapperMockRecorder struct {
	mock *MockTaskOpWrapper
}

// NewMockTaskOpWrapper creates a new mock instance
func NewMockTaskOpWrapper(ctrl *gomock.Controller) *MockTaskOpWrapper {
	mock := &MockTaskOpWrapper{ctrl: ctrl}
	mock.recorder = &MockTaskOpWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTaskOpWrapper) EXPECT() *MockTaskOpWrapperMockRecorder {
	return m.recorder
}

// List mocks base method
func (m *MockTaskOpWrapper) List(tasklistid string, opts ...googleapi.CallOption) (*v1.Tasks, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*v1.Tasks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockTaskOpWrapperMockRecorder) List(tasklistid interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskOpWrapper)(nil).List), varargs...)
}

// Insert mocks base method
func (m *MockTaskOpWrapper) Insert(tasklistid string, task *v1.Task, opts ...googleapi.CallOption) (*v1.Task, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid, task}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(*v1.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockTaskOpWrapperMockRecorder) Insert(tasklistid, task interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid, task}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTaskOpWrapper)(nil).Insert), varargs...)
}

// Update mocks base method
func (m *MockTaskOpWrapper) Update(tasklistid, taskid string, task *v1.Task, opts ...googleapi.CallOption) (*v1.Task, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid, taskid, task}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*v1.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockTaskOpWrapperMockRecorder) Update(tasklistid, taskid, task interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid, taskid, task}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskOpWrapper)(nil).Update), varargs...)
}

// Delete mocks base method
func (m *MockTaskOpWrapper) Delete(tasklistid, taskid string, opts ...googleapi.CallOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{tasklistid, taskid}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockTaskOpWrapperMockRecorder) Delete(tasklistid, taskid interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tasklistid, taskid}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskOpWrapper)(nil).Delete), varargs...)
}
